# Generated by Django 5.1.3 on 2024-12-03 10:19

import referral.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='other_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=referral.models.generate_referral_code, max_length=6, unique=True),
        ),
    ]
